### ISSUE TITLE
Problem with metrics calculation and testing after refactoring

### ISSUE THREAD

**Issue by leahcimali** [leahcimali/Federated-Traffic-Flow-Forecasting#45]
Recently, a bug was introduced that caused incorrect calculations for metrics of preregistered models. As a result, the calculated metrics are no longer consistent. This issue was working fine until the last commit on June 27th ([7c85a1fe51254f00e83f063d5e3223b207c55e28](https://github.com/leahcimali/Federated-Traffic-Flow-Forecasting/commit/7c85a1fe51254f00e83f063d5e3223b207c55e28)), but problems emerged afterwards. To resolve this, there are two possible approaches: either revert to an older commit or locate the bug in the current codebase.

**Comment by Desmoniak** [comment]
I have identified the issue in preprocess_PeMS_data() function from utils.data.py. In the specific commit ID you provided, there is a piece of code that was introduced a long time ago and now removed in main.py and placed in preprocess_PeMS_data() in the commit ID that you give.
Here the piece of code:
`df_PeMS = df_PeMS[:int(len(df_PeMS) * time_serie_percentage_length)]`
The signature of preprocess_PeMS_data() is here:
`preprocess_PeMS_data(df_PeMS, time_serie_percentage_length, df_distance, init_node : int = 0, n_neighbors : int = 99, smooth = True, center_and_reduce = False, normalize = False, sort_by_mean = True)`
However, the problem arises in test.py where preprocess_PeMS_data() is also used, but it never utilizes the reduced version of the time series. Instead, it always uses 100% of the time series. To fix this bug, we need to introduce a set time_serie_percentage_length to ensure that the function always operates on the full 100% of the time series. So call `preprocess_PeMS_data(df_PeMS, time_serie_percentage_length, df_distance, init_node : int = 0, n_neighbors : int = 99, smooth = True, center_and_reduce = False, normalize = False, sort_by_mean = True)` with time_serie_percentage_length=1 in test.py.
