### ISSUE TITLE
There is a problem when imports are placed before the docstrings.

### ISSUE THREAD

**Issue by Desmoniak** [leahcimali/Federated-Traffic-Flow-Forecasting#9]
```python
def preprocess_PeMS_data(df_PeMS, df_distance, init_node : int = 0, n_neighbors : int = 99, smooth = True, center_and_reduce = False, normalize = False,sort_by_mean = True):
    from src.utils_graph import create_graph, subgraph_dijkstra, compute_adjacency_matrix
    """
    Filter to n nearest neightbors from 'init_node', sort by mean traffic flow, and normalize and smooth data

    Parameters
    ----------
    init_node : int
        Index of the node we want to start with

    n_neighbors: int
        Number of nearest neighbors to consider

    Returns
    ----------
    df_PeMS :
        PeMS that have been preprocessed

    adjacency_matrix : array
        the adjacency matrix of PeMS
    """
```
I don’t know if it’s just with VS Code, but when you put the import right before the docstring, VS Code doesn’t print the documentation of the function.
Here, with the imports set before the docstrings :
![image](https://github.com/leahcimali/Federated-Traffic-Flow-Forecasting/assets/60919643/a3a44810-0bc7-4215-9505-53f08165b485)
with the imports set after the docstrings :
![image](https://github.com/leahcimali/Federated-Traffic-Flow-Forecasting/assets/60919643/5abfbb39-0b2d-461e-bb73-19c6adbe6c06)

**Comment by omar-rifai** [comment]
Good catch, will try to keep that in mind for the future.
